name: Python benchmarks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: gh-docs
          path: gh-docs
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: snok/install-poetry@v1
      - run: poetry install --no-interaction
        working-directory: py
      - run: poetry run pytest --benchmark-enable --benchmark-only --benchmark-histogram=../gh-docs/benchmark
        working-directory: py
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: gh-docs
          add: benchmark.svg
          message: 'pytest-benchmark ${{ github.sha }}'
