name: Python CI

on:
  push:
    branches: [ main ]
    paths: [ dsa_and_algorithms/**, coding_interview_problems/**, competitive_programming_problems/**, curated_list_of_75_leetcode_problems/**, amazon_interview_prep/**, facebook_interview_prep/** ]
  pull_request:
    branches: [ main ]
    paths: [ dsa_and_algorithms/**, coding_interview_problems/**, competitive_programming_problems/**, curated_list_of_75_leetcode_problems/**, amazon_interview_prep/**, facebook_interview_prep/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: snok/install-poetry@v1
      - run: poetry install --no-interaction
        working-directory: py
      - run: poetry run pylint aoc2022
        working-directory: py
      - run: poetry run black . --check
        working-directory: py
      - run: poetry run isort . --check
        working-directory: py
      - run: poetry run pytest --benchmark-skip
        working-directory: py
